### ISSUE TITLE
Capturing exposure events

### ISSUE THREAD

**Issue by richbai90** [UAA-Robo/tree-ring#2]
Hello,

I am writing because you are the only repo on Github I could find that was actively maintaining a project that utilizes the Amscope API. I'm using the AMCAM_EVENT_EXPO_START and AMCAM_EVENT_EXPO_END events, respectively, but they are not triggered when using pull mode, at least not when the camera is in video mode. Have you tried to use these events or other events besides AMCAM_EVENT_IMAGE in your work?

**Comment by Dawson-Packer** [comment]
Our project has only used AMCAM_EVENT_IMAGE so far so I’m sorry to say we can’t help you. If we learn anything new, we’ll make sure to send it your way.

**Comment by richbai90** [comment]
It's not supported with our camera. Closing, but thank you for replying.
